In [2]:
%pip install unsloth

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unsloth in /home/jupyter/.local/lib/python3.10/site-packages (2025.9.10)
Requirement already satisfied: unsloth_zoo>=2025.9.13 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (2025.9.13)
Requirement already satisfied: torch>=2.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (2.8.0)
Requirement already satisfied: xformers>=0.0.27.post2 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.0.32.post2)
Requirement already satisfied: bitsandbytes in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.47.0)
Requirement already satisfied: triton>=3.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (3.4.0)
Requirement already satisfied: packaging in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (25.0)
Requirement already satisfied: tyro in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.9.32)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (4.56.2)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,>=3.4.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (4.1.1)
Requirement already satisfied: sentencepiece>=0.2.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.2.1)
Requirement already satisfied: tqdm in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (4.67.1)
Requirement already satisfied: psutil in /kernel/lib/python3.10/site-packages (from unsloth) (7.1.0)
Requirement already satisfied: wheel>=0.42.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.45.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from unsloth) (1.22.4)
Requirement already satisfied: accelerate>=0.34.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (1.10.1)
Requirement already satisfied: trl!=0.15.0,!=0.19.0,!=0.9.0,!=0.9.1,!=0.9.2,!=0.9.3,<=0.23.0,>=0.7.9 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.23.0)
Requirement already satisfied: peft!=0.11.0,>=0.7.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.17.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from unsloth) (3.20.3)
Requirement already satisfied: huggingface_hub>=0.34.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.35.3)
Requirement already satisfied: hf_transfer in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.35.1)
Requirement already satisfied: torchvision in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.23.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (3.12.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (2022.10.31)
Requirement already satisfied: requests in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.34.0->unsloth) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface_hub>=0.34.0->unsloth) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface_hub>=0.34.0->unsloth) (1.1.10)
Requirement already satisfied: pyarrow>=21.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.5.3)
Requirement already satisfied: xxhash in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (3.8.5)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.3.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.10/dist-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (2023.7.22)
Requirement already satisfied: sympy>=1.13.3 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.4.0->unsloth) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.4.0->unsloth) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth) (1.13.1.3)
Requirement already satisfied: setuptools>=40.8.0 in /kernel/lib/python3.10/site-packages (from triton>=3.0.0->unsloth) (65.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: torchao in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth_zoo>=2025.9.13->unsloth) (0.13.0)
Requirement already satisfied: cut_cross_entropy in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth_zoo>=2025.9.13->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from unsloth_zoo>=2025.9.13->unsloth) (9.4.0)
Requirement already satisfied: msgspec in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth_zoo>=2025.9.13->unsloth) (0.19.0)
Requirement already satisfied: importlib_metadata in /usr/lib/python3/dist-packages (from diffusers->unsloth) (4.6.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.4.0->unsloth) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.16.0)
Requirement already satisfied: docstring-parser>=0.15 in /home/jupyter/.local/lib/python3.10/site-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: rich>=11.1.0 in /usr/local/lib/python3.10/dist-packages (from tyro->unsloth) (13.4.2)
Requirement already satisfied: shtab>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from tyro->unsloth) (1.6.4)
Requirement already satisfied: typeguard>=4.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1.0->tyro->unsloth) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1.0->tyro->unsloth) (2.14.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=11.1.0->tyro->unsloth) (0.1.2)

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip

In [3]:
%pip install --upgrade unsloth-zoo
%pip install --upgrade unsloth

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unsloth-zoo in /home/jupyter/.local/lib/python3.10/site-packages (2025.9.13)
Requirement already satisfied: torch>=2.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (2.8.0)
Requirement already satisfied: torchao in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.13.0)
Requirement already satisfied: triton in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (3.4.0)
Requirement already satisfied: packaging>=24.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (25.0)
Requirement already satisfied: tyro in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.9.32)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (4.56.2)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,>=3.4.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (4.1.1)
Requirement already satisfied: sentencepiece>=0.2.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.2.1)
Requirement already satisfied: tqdm in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (4.67.1)
Requirement already satisfied: psutil in /kernel/lib/python3.10/site-packages (from unsloth-zoo) (7.1.0)
Requirement already satisfied: wheel>=0.42.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.45.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from unsloth-zoo) (1.22.4)
Requirement already satisfied: accelerate>=0.34.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (1.10.1)
Requirement already satisfied: trl!=0.15.0,!=0.19.0,!=0.9.0,!=0.9.1,!=0.9.2,!=0.9.3,<=0.23.0,>=0.7.9 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.23.0)
Requirement already satisfied: peft!=0.11.0,>=0.7.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.17.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from unsloth-zoo) (3.20.3)
Requirement already satisfied: huggingface_hub>=0.34.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.35.3)
Requirement already satisfied: hf_transfer in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.1.9)
Requirement already satisfied: cut_cross_entropy in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from unsloth-zoo) (9.4.0)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from unsloth-zoo) (2022.10.31)
Requirement already satisfied: msgspec in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (0.19.0)
Requirement already satisfied: typing_extensions in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth-zoo) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth-zoo) (3.12.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth-zoo) (6.0.1)
Requirement already satisfied: requests in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth-zoo) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth-zoo) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth-zoo) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.34.0->unsloth-zoo) (2023.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface_hub>=0.34.0->unsloth-zoo) (1.1.10)
Requirement already satisfied: pyarrow>=21.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (1.5.3)
Requirement already satisfied: xxhash in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (3.8.5)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (1.3.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.10/dist-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth-zoo) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth-zoo) (2023.7.22)
Requirement already satisfied: sympy>=1.13.3 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.4.0->unsloth-zoo) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.4.0->unsloth-zoo) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/jupyter/.local/lib/python3.10/site-packages (from torch>=2.4.0->unsloth-zoo) (1.13.1.3)
Requirement already satisfied: setuptools>=40.8.0 in /kernel/lib/python3.10/site-packages (from triton->unsloth-zoo) (65.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth-zoo) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.4.0->unsloth-zoo) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth-zoo) (1.16.0)
Requirement already satisfied: docstring-parser>=0.15 in /home/jupyter/.local/lib/python3.10/site-packages (from tyro->unsloth-zoo) (0.17.0)
Requirement already satisfied: rich>=11.1.0 in /usr/local/lib/python3.10/dist-packages (from tyro->unsloth-zoo) (13.4.2)
Requirement already satisfied: shtab>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from tyro->unsloth-zoo) (1.6.4)
Requirement already satisfied: typeguard>=4.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from tyro->unsloth-zoo) (4.4.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1.0->tyro->unsloth-zoo) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1.0->tyro->unsloth-zoo) (2.14.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=11.1.0->tyro->unsloth-zoo) (0.1.2)

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unsloth in /home/jupyter/.local/lib/python3.10/site-packages (2025.9.10)
Requirement already satisfied: unsloth_zoo>=2025.9.13 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (2025.9.13)
Requirement already satisfied: torch>=2.4.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (2.8.0)
Requirement already satisfied: xformers>=0.0.27.post2 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.0.32.post2)
Requirement already satisfied: bitsandbytes in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.47.0)
Requirement already satisfied: triton>=3.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (3.4.0)
Requirement already satisfied: packaging in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (25.0)
Requirement already satisfied: tyro in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.9.32)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (4.56.2)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,>=3.4.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (4.1.1)
Requirement already satisfied: sentencepiece>=0.2.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.2.1)
Requirement already satisfied: tqdm in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (4.67.1)
Requirement already satisfied: psutil in /kernel/lib/python3.10/site-packages (from unsloth) (7.1.0)
Requirement already satisfied: wheel>=0.42.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.45.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from unsloth) (1.22.4)
Requirement already satisfied: accelerate>=0.34.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (1.10.1)
Requirement already satisfied: trl!=0.15.0,!=0.19.0,!=0.9.0,!=0.9.1,!=0.9.2,!=0.9.3,<=0.23.0,>=0.7.9 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.23.0)
Requirement already satisfied: peft!=0.11.0,>=0.7.1 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.17.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from unsloth) (3.20.3)
Requirement already satisfied: huggingface_hub>=0.34.0 in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.35.3)
Requirement already satisfied: hf_transfer in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.35.1)
Requirement already satisfied: torchvision in /home/jupyter/.local/lib/python3.10/site-packages (from unsloth) (0.23.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (3.12.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (2022.10.31)
Requirement already satisfied: requests in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /home/jupyter/.local/lib/python3.10/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2,>=4.51.3->unsloth) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.34.0->unsloth) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface_hub>=0.34.0->unsloth) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/jupyter/.local/lib/python3.10/site-packages (from huggingface_hub>=0.34.0->unsloth) (1.1.10)
Requirement already satisfied: pyarrow>=21.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.5.3)
Requirement already satisfied: xxhash in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/jupyter/.local/lib/python3.10/site-packages (from datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (3.8.5)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (1.3.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.10/dist-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,>=3.4.1->unsloth) (3.4)

In [3]:
%pip install ipywidgets -U

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.10/dist-packages (7.7.1)
Collecting ipywidgets
  Downloading ipywidgets-8.1.7-py3-none-any.whl.metadata (2.4 kB)
Collecting comm>=0.1.3 (from ipywidgets)
  Downloading comm-0.2.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (7.34.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (5.7.1)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Downloading widgetsnbextension-4.0.14-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.15-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: setuptools>=18.5 in /kernel/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (65.5.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (0.19.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (3.0.39)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (2.14.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (4.8.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=6.1.0->ipywidgets) (0.2.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Downloading ipywidgets-8.1.7-py3-none-any.whl (139 kB)
Downloading jupyterlab_widgets-3.0.15-py3-none-any.whl (216 kB)
Downloading widgetsnbextension-4.0.14-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 22.7 MB/s  0:00:00
Downloading comm-0.2.3-py3-none-any.whl (7.3 kB)
Installing collected packages: widgetsnbextension, jupyterlab_widgets, comm, ipywidgets
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [ipywidgets]4 [ipywidgets]widgets]
Successfully installed comm-0.2.3 ipywidgets-8.1.7 jupyterlab_widgets-3.0.15 widgetsnbextension-4.0.14

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip

In [ ]:
!jupyter nbextension enable --py widgetsnbextension

In [1]:
!nvidia-smi

Thu Oct  2 13:35:39 2025
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.261.03             Driver Version: 535.261.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  | 00000000:8C:00.0 Off |                    0 |
| N/A   28C    P0              71W / 500W |      9MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1180      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+

## Data

In [2]:
import json
import pandas as pd
import numpy as np

import glob
import os

# from tqdm.autonotebook import tqmd

In [3]:
# df = pd.read_csv("data/data_latest.csv")

# df

### creating dataset

In [4]:
from unsloth import FastModel
import torch

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/home/jupyter/.local/lib/python3.10/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
2025-10-02 13:37:30.057522: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-02 13:37:35.710559: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

🦥 Unsloth Zoo will now patch everything to make training faster!

In [ ]:
max_seq_length = 4096

model, tokenizer = FastModel.from_pretrained(
    model_name = "unsloth/gemma-3-270m-it",
    max_seq_length = max_seq_length, # Choose any for long context!
    # load_in_4bit = False,  # 4 bit quantization to reduce memory
    # load_in_8bit = False, # [NEW!] A bit more accurate, uses 2x memory
    full_finetuning = True, # [NEW!] We have full finetuning now!
    token = "token", # use one if using gated models
)

Unsloth: You selected full finetuning support, but 4bit / 8bit is enabled - disabling LoRA / QLoRA.
==((====))==  Unsloth 2025.9.10: Fast Gemma3 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.325 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Gemma3 does not support SDPA - switching to fast eager.
Unsloth: Using bfloat16 full finetuning which cuts memory usage by 50%.

In [6]:
# model = FastModel.get_peft_model(
#     model,
#     r = 128, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
#     target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
#                       "gate_proj", "up_proj", "down_proj",],
#     lora_alpha = 128,
#     lora_dropout = 0, # Supports any, but = 0 is optimized
#     bias = "none",    # Supports any, but = "none" is optimized
#     # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
#     use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
#     random_state = 3407,
#     use_rslora = False,  # We support rank stabilized LoRA
#     loftq_config = None, # And LoftQ
# )

In [7]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "gemma3",
)

In [8]:
# print(df["review_text"][df["review_id"] == 573263].values)

In [9]:
# synth_data

In [10]:
# {int(synth_data[i]["id"]) : synth_data[i]["topic_sentiment_pairs"] for i in range(10)}

In [15]:
SYSTEM_PROMPT = """\
Проанализируй отзыв клиента Газпромбанка (ГПБ) и определи:
1. Упоминаемые тем ("topic") из списка допустимых тем;
2. Тональность ("sentiment") для каждой темы: positive/negative/neutral.

ПРАВИЛА:
- Тональность: `neutral` указывается тогда, когда тема упомянута как факт, без эмоциональной окраски.
- Не выдумывай темы: Если в отзыве нет явного упоминания продукта или услуги, не включай его.
- Если темы нет: Если невозможно определить ни одну тему, верни пустой массив [].
- Темы: Используй ТОЛЬКО следующий список тем и подтем. Не добавляй новые темы.
- Уникальность тем: Одна тема может встречаться только один раз.

ДОПУСТИМЫЕ ТЕМЫ:
- Офисное обслуживание (обслуживание в отделениях банка)
- Дистанционное обслуживание (звонки, чаты, онлайн-консультации и подобное)
- Банкоматы
- Курьерская доставка карт
- Обмен валют
- Дебетовые карты (включая подтемы: Денежные переводы, Карта UnionPay, Умная дебетовая карта «Мир», Премиальная карта Mir Supreme)
- Кредитные карты (включая подтемы: Кредитная карта 180 дней Премиум)
- Кредиты (включая подтемы: Кредит наличными, Кредит наличными под залог недвижимости, Кредит под залог автомобиля)
- Рефинансирование/Реструктуризация (включая подтемы: Рефинансирование кредитов, Реструктуризация кредитов, Рефинансирование ипотеки, Реструктуризация ипотеки)
- Автокредиты
- Ипотека
- Страховые и сервисные продукты
- Вклады (включая подтемы: Вклад «Копить», Вклад «В Плюсе», Вклад «Новые деньги»)
- Накопительные счета (включая подтемы: Накопительный счёт «Ежедневная выгода», Накопительный счёт «Ежедневный процент», Накопительный счёт «Премиум»)
- Акции и бонусы (включая подтемы: Газпром Бонус, Газпромбанк Привилегии, Кэшбэк, Акции, Программы лояльности)
- Газпромбанк Премиум (включая подтемы: Персональный менеджер, Консьерж-сервис, Премиальное обслуживание)
- Мобильное приложение
- Другие услуги банка (включая подтемы: Газпромбанк Travel (покупка авиабилетов/отелей), Gazprom Pay (оплата телефоном), GorodPay (оплата общественного транспорта), Инвестиционные продукты, Брокерские услуги, Депозитарные услуги, Аренда сейфовых ячеек)

Примеры:
Отзыв: "В отделении грубо обслужили, но мобильное приложение удобное"
[
{"topic": "Офисное обслуживание", "sentiment": "negative"},
{"topic": "Мобильное приложение", "sentiment": "positive"}
]

Отзыв: "Курьер не пришёл на встречу. По телефону не смогли помочь."
[
{"topic": "Курьерская доставка карт", "sentiment": "negative"},
{"topic": "Дистанционное обслуживание", "sentiment": "negative"}
]

Отзыв: "Оформил Премиальную карту Mir Supreme через приложение"
[
{"topic": "Премиальная карта Mir Supreme", "sentiment": "neutral"},
{"topic": "Дебетовые карты", "sentiment": "neutral"},
{"topic": "Газпромбанк Премиум", "sentiment": "neutral"},
{"topic": "Мобильное приложение", "sentiment": "neutral"}
]

Отзыв: "Пользуюсь Газпромбанк Travel для бронирования отелей и Gazprom Pay для оплаты"
[
{"topic": "Другие услуги банка", "sentiment": "neutral"},
{"topic": "Газпромбанк Travel", "sentiment": "neutral"},
{"topic": "Gazprom Pay", "sentiment": "neutral"}
]

Проанализируй следующий отзыв:
"""

In [16]:
# Сдеалть разделение на train/test по дате

from datasets import Dataset

topics_sentiments_json = "dataset_v2.json"
# original_reviews_csv = "mount/data/data_latest.csv"

with open(topics_sentiments_json) as f:
    topics_sentiments_full = json.load(f)
    
# topics_sentiments_pair = {
#     int(topics_sentiments_full[i]["id"]) : topics_sentiments_full[i]["topic_sentiment_pairs"] 
#     for i in range(len(topics_sentiments_full))
# }

# original_reviews_df = pd.read_csv(original_reviews_csv)


user_prompts = []
assistant_answers = []

for i in range(len(topics_sentiments_full)):
    # original_review_series = original_reviews_df.iloc[i]
    # review_id = original_review_series["review_id"]

    # user_prompt = original_review_series["review_text"]
    
    user_prompt = topics_sentiments_full[i]["review_text"]

    assistant_answer = str(topics_sentiments_full[i]["topic_sentiment_pairs"])
    
    user_prompts.append(user_prompt)
    assistant_answers.append(assistant_answer)
    

dataset_dict = {"user_prompt" : user_prompts, "assistant_answer" : assistant_answers}

dataset = Dataset.from_dict(dataset_dict)

In [17]:
dataset = dataset.train_test_split(test_size=0.1, shuffle=True)

dataset_train = dataset["train"]
dataset_test = dataset["test"]

In [18]:
dataset_train[100]

{'user_prompt': 'Здравствуйте. Спасибо большое Огаджанян Татьяне за оказанную услугу - доставка карты. Очень хорошая девочка! Звонила утром, представилась, договорились о встрече. За 20 минут до приезда - дополнительный звонок.  Всё хорошо объяняет, четко по делу. Помогла определиться с выбором вклада! Не отказала в просьбе, хотя очень спешила - канун праздника, а ещё много клиентов. Большая молодец! Спасибо 🙏!',
 'assistant_answer': "[{'topic': 'Курьерская доставка карт', 'sentiment': 'positive'}, {'topic': 'Вклады', 'sentiment': 'positive'}]"}

In [19]:
def convert_to_chatml(example):
    return {
        "conversations": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": example["user_prompt"]},
            {"role": "assistant", "content": example["assistant_answer"]}
        ]
    }

dataset_train = dataset_train.map(
    convert_to_chatml
)

dataset_test = dataset_test.map(
    convert_to_chatml
)

Map: 100%|██████████| 10389/10389 [00:01<00:00, 8947.20 examples/s]
Map: 100%|██████████| 1155/1155 [00:00<00:00, 9868.09 examples/s]

In [20]:
def formatting_prompts_func(examples):
    convos = examples["conversations"]
    texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False).removeprefix('<bos>') for convo in convos]
    return { "text" : texts, }

dataset_train = dataset_train.map(formatting_prompts_func, batched = True)

dataset_test = dataset_test.map(formatting_prompts_func, batched = True)

Map: 100%|██████████| 10389/10389 [00:01<00:00, 7407.63 examples/s]
Map: 100%|██████████| 1155/1155 [00:00<00:00, 7626.45 examples/s]

## training

In [21]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset_train,
    eval_dataset = dataset_test, # Can set up evaluation!
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 16,
        gradient_accumulation_steps = 2, # Use GA to mimic batch size!
        warmup_steps = 5,
        num_train_epochs = 2, # Set this for 1 full training run.
        # max_steps = 100,
        learning_rate = 2e-5, # Reduce to 2e-5 for long training runs
        logging_steps = 50,
        optim = "adamw_8bit",
        weight_decay = 0.015,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir="gemma-3-270m-it-revews-fine-tune-v3",
        report_to = "none", # Use this for WandB etc
        dataset_num_proc=0,
        do_eval=True,
        eval_strategy="steps",
        eval_steps=0.2,
    ),
)

Unsloth: Tokenizing ["text"]: 100%|██████████| 10389/10389 [00:05<00:00, 1823.87 examples/s]
Unsloth: Tokenizing ["text"]: 100%|██████████| 1155/1155 [00:00<00:00, 1939.51 examples/s]

In [22]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<start_of_turn>user\n",
    response_part = "<start_of_turn>model\n",
    num_proc=0,
)

Map: 100%|██████████| 10389/10389 [00:10<00:00, 1030.19 examples/s]
Map: 100%|██████████| 1155/1155 [00:01<00:00, 1060.30 examples/s]

In [ ]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,389 | Num Epochs = 2 | Total steps = 650
O^O/ \_/ \    Batch size per device = 16 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (16 x 2 x 1) = 32
 "-____-"     Trainable parameters = 268,098,176 of 268,098,176 (100.00% trained)
  0%|          | 0/650 [00:00<?, ?it/s]

Unsloth: Will smartly offload gradients to save VRAM!

  8%|▊         | 50/650 [02:56<27:43,  2.77s/it]

{'loss': 0.2563, 'grad_norm': 5.1875, 'learning_rate': 1.863565891472868e-05, 'epoch': 0.15}

 15%|█▌        | 100/650 [05:17<24:43,  2.70s/it]

{'loss': 0.1496, 'grad_norm': 4.21875, 'learning_rate': 1.708527131782946e-05, 'epoch': 0.31}

 20%|██        | 130/650 [06:44<24:52,  2.87s/it]Unsloth: Not an error, but Gemma3TextModel does not accept `num_items_in_batch`.
Using gradient accumulation will be very slightly less accurate.
Read more on gradient accumulation issues here: https://unsloth.ai/blog/gradient

  0%|          | 0/289 [00:00<?, ?it/s]
  1%|          | 3/289 [00:00<01:00,  4.74it/s]
  2%|▏         | 5/289 [00:01<01:10,  4.01it/s]
  2%|▏         | 7/289 [00:01<01:00,  4.68it/s]
  3%|▎         | 9/289 [00:01<00:55,  5.02it/s]
  4%|▍         | 11/289 [00:02<00:53,  5.22it/s]
  4%|▍         | 13/289 [00:02<00:49,  5.57it/s]
  5%|▌         | 15/289 [00:02<00:47,  5.72it/s]
  6%|▌         | 17/289 [00:03<00:47,  5.73it/s]
  7%|▋         | 19/289 [00:03<00:46,  5.82it/s]
  7%|▋         | 21/289 [00:03<00:43,  6.18it/s]
  8%|▊         | 23/289 [00:04<00:42,  6.28it/s]
  9%|▊         | 25/289 [00:04<00:42,  6.20it/s]
  9%|▉         | 27/289 [00:04<00:42,  6.15it/s]
 10%|█         | 29/289 [00:05<00:42,  6.09it/s]
 11%|█         | 31/289 [00:05<00:42,  6.11it/s]
 11%|█▏        | 33/289 [00:05<00:42,  6.06it/s]
 12%|█▏        | 35/289 [00:06<00:41,  6.11it/s]
 13%|█▎        | 37/289 [00:06<00:42,  5.94it/s]
 13%|█▎        | 39/289 [00:06<00:46,  5.42it/s]
 14%|█▍        | 41/289 [00:07<00:46,  5.36it/s]
 15%|█▍        | 43/289 [00:07<00:44,  5.48it/s]
 16%|█▌        | 45/289 [00:08<00:43,  5.58it/s]
 16%|█▋        | 47/289 [00:08<00:41,  5.79it/s]
 17%|█▋        | 49/289 [00:08<00:40,  5.95it/s]
 18%|█▊        | 51/289 [00:08<00:38,  6.26it/s]
 18%|█▊        | 53/289 [00:09<00:37,  6.22it/s]
 19%|█▉        | 55/289 [00:09<00:37,  6.31it/s]
 20%|█▉        | 57/289 [00:09<00:37,  6.12it/s]
 20%|██        | 59/289 [00:10<00:36,  6.23it/s]
 21%|██        | 61/289 [00:10<00:35,  6.45it/s]
 22%|██▏       | 63/289 [00:10<00:35,  6.29it/s]
 22%|██▏       | 65/289 [00:11<00:38,  5.85it/s]
 23%|██▎       | 67/289 [00:11<00:40,  5.51it/s]
 24%|██▍       | 69/289 [00:11<00:37,  5.84it/s]
 25%|██▍       | 71/289 [00:12<00:38,  5.68it/s]
 25%|██▌       | 73/289 [00:12<00:38,  5.66it/s]
 26%|██▌       | 75/289 [00:12<00:37,  5.72it/s]
 27%|██▋       | 77/289 [00:13<00:36,  5.74it/s]
 27%|██▋       | 79/289 [00:13<00:34,  6.02it/s]
 28%|██▊       | 81/289 [00:13<00:35,  5.88it/s]
 29%|██▊       | 83/289 [00:14<00:34,  6.00it/s]
 29%|██▉       | 85/289 [00:14<00:33,  6.02it/s]
 30%|███       | 87/289 [00:14<00:32,  6.13it/s]
 31%|███       | 89/289 [00:15<00:32,  6.19it/s]
 31%|███▏      | 91/289 [00:15<00:32,  6.05it/s]
 32%|███▏      | 93/289 [00:16<00:34,  5.68it/s]
 33%|███▎      | 95/289 [00:16<00:35,  5.40it/s]
 34%|███▎      | 97/289 [00:16<00:32,  5.91it/s]
 34%|███▍      | 99/289 [00:17<00:31,  5.96it/s]
 35%|███▍      | 101/289 [00:17<00:30,  6.13it/s]
 36%|███▌      | 103/289 [00:17<00:31,  5.93it/s]
 36%|███▋      | 105/289 [00:17<00:29,  6.30it/s]
 37%|███▋      | 107/289 [00:18<00:28,  6.36it/s]
 38%|███▊      | 109/289 [00:18<00:28,  6.24it/s]
 38%|███▊      | 111/289 [00:18<00:30,  5.91it/s]
 39%|███▉      | 113/289 [00:19<00:29,  5.98it/s]
 40%|███▉      | 115/289 [00:19<00:31,  5.58it/s]
 40%|████      | 117/289 [00:20<00:28,  6.01it/s]
 41%|████      | 119/289 [00:20<00:28,  6.02it/s]
 42%|████▏     | 121/289 [00:20<00:26,  6.27it/s]
 43%|████▎     | 123/289 [00:21<00:29,  5.68it/s]
 43%|████▎     | 125/289 [00:21<00:28,  5.76it/s]
 44%|████▍     | 127/289 [00:21<00:28,  5.63it/s]
 45%|████▍     | 129/289 [00:22<00:26,  5.99it/s]
 45%|████▌     | 131/289 [00:22<00:25,  6.23it/s]
 46%|████▌     | 133/289 [00:22<00:25,  6.19it/s]
 47%|████▋     | 135/289 [00:23<00:26,  5.83it/s]
 47%|████▋     | 137/289 [00:23<00:25,  5.93it/s]
 48%|████▊     | 139/289 [00:23<00:24,  6.05it/s]
 49%|████▉     | 141/289 [00:24<00:24,  6.11it/s]
 49%|████▉     | 143/289 [00:24<00:22,  6.40it/s]
 50%|█████     | 145/289 [00:24<00:22,  6.37it/s]
 51%|█████     | 147/289 [00:24<00:22,  6.40it/s]
 52%|█████▏    | 149/289 [00:25<00:22,  6.28it/s]
 52%|█████▏    | 151/289 [00:25<00:22,  6.05it/s]
 53%|█████▎    | 153/289 [00:25<00:23,  5.77it/s]
 54%|█████▎    | 155/289 [00:26<00:23,  5.78it/s]
 54%|█████▍    | 157/289 [00:26<00:21,  6.02it/s]
 55%|█████▌    | 159/289 [00:26<00:21,  5.92it/s]
 56%|█████▌    | 161/289 [00:27<00:20,  6.13it/s]
 56%|█████▋    | 163/289 [00:27<00:20,  6.02it/s]
 57%|█████▋    | 165/289 [00:27<00:20,  5.99it/s]
 58%|█████▊    | 167/289 [00:28<00:20,  5.90it/s]
 58%|█████▊    | 169/289 [00:28<00:19,  6.09it/s]
 59%|█████▉    | 171/289 [00:29<00:21,  5.61it/s]
 60%|█████▉    | 173/289 [00:29<00:20,  5.64it/s]
 61%|██████    | 175/289 [00:29<00:19,  5.79it/s]
 61%|██████    | 177/289 [00:30<00:18,  6.03it/s]
 62%|██████▏   | 179/289 [00:30<00:18,  5.79it/s]
 63%|██████▎   | 181/289 [00:30<00:18,  5.78it/s]
 63%|██████▎   | 183/289 [00:31<00:17,  5.95it/s]
 64%|██████▍   | 185/289 [00:31<00:18,  5.71it/s]
 65%|██████▍   | 187/289 [00:31<00:16,  6.05it/s]
 65%|██████▌   | 189/289 [00:32<00:16,  5.98it/s]
 66%|██████▌   | 191/289 [00:32<00:16,  6.07it/s]
 67%|██████▋   | 193/289 [00:32<00:16,  5.97it/s]
 67%|██████▋   | 195/289 [00:33<00:15,  6.05it/s]
 68%|██████▊   | 197/289 [00:33<00:15,  6.07it/s]
 69%|██████▉   | 199/289 [00:33<00:15,  5.67it/s]
 70%|██████▉   | 201/289 [00:34<00:15,  5.80it/s]
 70%|███████   | 203/289 [00:34<00:14,  5.86it/s]
 71%|███████   | 205/289 [00:34<00:14,  5.84it/s]
 72%|███████▏  | 207/289 [00:35<00:13,  5.96it/s]
 72%|███████▏  | 209/289 [00:35<00:13,  5.75it/s]
 73%|███████▎  | 211/289 [00:35<00:13,  5.71it/s]
 74%|███████▎  | 213/289 [00:36<00:13,  5.49it/s]
 74%|███████▍  | 215/289 [00:36<00:13,  5.53it/s]
 75%|███████▌  | 217/289 [00:36<00:12,  5.61it/s]
 76%|███████▌  | 219/289 [00:37<00:11,  5.89it/s]
 76%|███████▋  | 221/289 [00:37<00:12,  5.46it/s]
 77%|███████▋  | 223/289 [00:37<00:11,  5.76it/s]
 78%|███████▊  | 225/289 [00:38<00:10,  5.96it/s]
 79%|███████▊  | 227/289 [00:38<00:10,  6.11it/s]
 79%|███████▉  | 229/289 [00:38<00:10,  5.89it/s]
 80%|███████▉  | 231/289 [00:39<00:09,  5.80it/s]
 81%|████████  | 233/289 [00:39<00:09,  5.73it/s]
 81%|████████▏ | 235/289 [00:39<00:09,  5.92it/s]
 82%|████████▏ | 237/289 [00:40<00:08,  5.92it/s]
 83%|████████▎ | 239/289 [00:40<00:08,  5.58it/s]
 83%|████████▎ | 241/289 [00:41<00:08,  5.44it/s]
 84%|████████▍ | 243/289 [00:41<00:08,  5.39it/s]
 85%|████████▍ | 245/289 [00:41<00:07,  5.78it/s]
 85%|████████▌ | 247/289 [00:42<00:07,  5.93it/s]
 86%|████████▌ | 249/289 [00:42<00:06,  5.90it/s]
 87%|████████▋ | 251/289 [00:42<00:06,  5.81it/s]
 88%|████████▊ | 253/289 [00:43<00:06,  5.93it/s]
 88%|████████▊ | 255/289 [00:43<00:05,  5.90it/s]
 89%|████████▉ | 257/289 [00:43<00:05,  5.86it/s]
 90%|████████▉ | 259/289 [00:44<00:05,  5.92it/s]
 90%|█████████ | 261/289 [00:44<00:04,  6.05it/s]
 91%|█████████ | 263/289 [00:44<00:04,  6.34it/s]
 92%|█████████▏| 265/289 [00:45<00:03,  6.01it/s]
 92%|█████████▏| 267/289 [00:45<00:03,  6.20it/s]
 93%|█████████▎| 269/289 [00:45<00:03,  6.15it/s]
 94%|█████████▍| 271/289 [00:46<00:02,  6.13it/s]
 94%|█████████▍| 273/289 [00:46<00:02,  6.41it/s]
 95%|█████████▌| 275/289 [00:46<00:02,  6.15it/s]
 96%|█████████▌| 277/289 [00:47<00:02,  5.97it/s]
 97%|█████████▋| 279/289 [00:47<00:01,  5.98it/s]
 97%|█████████▋| 281/289 [00:47<00:01,  5.87it/s]
 98%|█████████▊| 283/289 [00:48<00:00,  6.02it/s]
 99%|█████████▊| 285/289 [00:48<00:00,  6.41it/s]
 99%|█████████▉| 287/289 [00:48<00:00,  6.13it/s]

 20%|██        | 130/650 [07:35<24:52,  2.87s/it]
100%|██████████| 289/289 [00:49<00:00,  5.97it/s]

{'eval_loss': 0.12228463590145111, 'eval_runtime': 51.2464, 'eval_samples_per_second': 22.538, 'eval_steps_per_second': 5.639, 'epoch': 0.4}

 23%|██▎       | 150/650 [08:32<24:52,  2.98s/it]

{'loss': 0.1278, 'grad_norm': 4.03125, 'learning_rate': 1.5534883720930232e-05, 'epoch': 0.46}

 31%|███       | 200/650 [10:58<21:55,  2.92s/it]

{'loss': 0.1162, 'grad_norm': 5.4375, 'learning_rate': 1.3984496124031008e-05, 'epoch': 0.62}

 38%|███▊      | 250/650 [13:22<19:35,  2.94s/it]

{'loss': 0.1102, 'grad_norm': 3.46875, 'learning_rate': 1.2434108527131783e-05, 'epoch': 0.77}

 40%|████      | 260/650 [13:52<18:24,  2.83s/it]
  0%|          | 0/289 [00:00<?, ?it/s]
  1%|          | 2/289 [00:00<00:20, 14.30it/s]
  1%|▏         | 4/289 [00:00<01:02,  4.58it/s]
  2%|▏         | 5/289 [00:01<01:26,  3.28it/s]
  2%|▏         | 7/289 [00:01<01:07,  4.19it/s]
  3%|▎         | 9/289 [00:01<00:59,  4.68it/s]
  4%|▍         | 11/289 [00:02<00:55,  4.97it/s]
  4%|▍         | 13/289 [00:02<00:51,  5.38it/s]
  5%|▌         | 15/289 [00:02<00:49,  5.58it/s]
  6%|▌         | 17/289 [00:03<00:48,  5.63it/s]
  7%|▋         | 19/289 [00:03<00:47,  5.73it/s]
  7%|▋         | 21/289 [00:03<00:43,  6.11it/s]
  8%|▊         | 23/289 [00:04<00:42,  6.22it/s]
  9%|▊         | 25/289 [00:04<00:42,  6.14it/s]
  9%|▉         | 27/289 [00:04<00:42,  6.10it/s]
 10%|█         | 29/289 [00:05<00:42,  6.06it/s]
 11%|█         | 31/289 [00:05<00:42,  6.06it/s]
 11%|█▏        | 33/289 [00:05<00:42,  6.02it/s]
 12%|█▏        | 35/289 [00:06<00:41,  6.08it/s]
 13%|█▎        | 37/289 [00:06<00:42,  5.91it/s]
 13%|█▎        | 39/289 [00:07<00:46,  5.39it/s]
 14%|█▍        | 41/289 [00:07<00:46,  5.33it/s]
 15%|█▍        | 43/289 [00:07<00:45,  5.44it/s]
 16%|█▌        | 45/289 [00:08<00:44,  5.54it/s]
 16%|█▋        | 47/289 [00:08<00:42,  5.76it/s]
 17%|█▋        | 49/289 [00:08<00:40,  5.92it/s]
 18%|█▊        | 51/289 [00:09<00:38,  6.22it/s]
 18%|█▊        | 53/289 [00:09<00:38,  6.18it/s]
 19%|█▉        | 55/289 [00:09<00:37,  6.27it/s]
 20%|█▉        | 57/289 [00:10<00:38,  6.09it/s]
 20%|██        | 59/289 [00:10<00:37,  6.20it/s]
 21%|██        | 61/289 [00:10<00:35,  6.41it/s]
 22%|██▏       | 63/289 [00:10<00:36,  6.25it/s]
 22%|██▏       | 65/289 [00:11<00:38,  5.82it/s]
 23%|██▎       | 67/289 [00:11<00:40,  5.49it/s]
 24%|██▍       | 69/289 [00:12<00:37,  5.81it/s]
 25%|██▍       | 71/289 [00:12<00:38,  5.64it/s]
 25%|██▌       | 73/289 [00:12<00:38,  5.62it/s]
 26%|██▌       | 75/289 [00:13<00:37,  5.67it/s]
 27%|██▋       | 77/289 [00:13<00:37,  5.70it/s]
 27%|██▋       | 79/289 [00:13<00:35,  5.98it/s]
 28%|██▊       | 81/289 [00:14<00:35,  5.86it/s]
 29%|██▊       | 83/289 [00:14<00:34,  5.96it/s]
 29%|██▉       | 85/289 [00:14<00:34,  5.98it/s]
 30%|███       | 87/289 [00:15<00:33,  6.10it/s]
 31%|███       | 89/289 [00:15<00:32,  6.15it/s]
 31%|███▏      | 91/289 [00:15<00:32,  6.03it/s]
 32%|███▏      | 93/289 [00:16<00:34,  5.66it/s]
 33%|███▎      | 95/289 [00:16<00:36,  5.38it/s]
 34%|███▎      | 97/289 [00:16<00:32,  5.87it/s]
 34%|███▍      | 99/289 [00:17<00:32,  5.93it/s]
 35%|███▍      | 101/289 [00:17<00:30,  6.08it/s]
 36%|███▌      | 103/289 [00:17<00:31,  5.89it/s]
 36%|███▋      | 105/289 [00:18<00:29,  6.25it/s]
 37%|███▋      | 107/289 [00:18<00:28,  6.31it/s]
 38%|███▊      | 109/289 [00:18<00:29,  6.19it/s]
 38%|███▊      | 111/289 [00:19<00:30,  5.88it/s]
 39%|███▉      | 113/289 [00:19<00:29,  5.94it/s]
 40%|███▉      | 115/289 [00:19<00:31,  5.55it/s]
 40%|████      | 117/289 [00:20<00:28,  5.98it/s]
 41%|████      | 119/289 [00:20<00:28,  5.98it/s]
 42%|████▏     | 121/289 [00:20<00:26,  6.24it/s]
 43%|████▎     | 123/289 [00:21<00:29,  5.65it/s]
 43%|████▎     | 125/289 [00:21<00:28,  5.73it/s]
 44%|████▍     | 127/289 [00:21<00:28,  5.60it/s]
 45%|████▍     | 129/289 [00:22<00:26,  5.96it/s]
 45%|████▌     | 131/289 [00:22<00:25,  6.20it/s]
 46%|████▌     | 133/289 [00:22<00:25,  6.15it/s]
 47%|████▋     | 135/289 [00:23<00:26,  5.80it/s]
 47%|████▋     | 137/289 [00:23<00:25,  5.90it/s]
 48%|████▊     | 139/289 [00:23<00:24,  6.01it/s]
 49%|████▉     | 141/289 [00:24<00:24,  6.08it/s]
 49%|████▉     | 143/289 [00:24<00:22,  6.38it/s]
 50%|█████     | 145/289 [00:24<00:22,  6.35it/s]
 51%|█████     | 147/289 [00:25<00:22,  6.38it/s]
 52%|█████▏    | 149/289 [00:25<00:22,  6.25it/s]
 52%|█████▏    | 151/289 [00:25<00:22,  6.02it/s]
 53%|█████▎    | 153/289 [00:26<00:23,  5.74it/s]
 54%|█████▎    | 155/289 [00:26<00:23,  5.75it/s]
 54%|█████▍    | 157/289 [00:26<00:22,  5.98it/s]
 55%|█████▌    | 159/289 [00:27<00:22,  5.89it/s]
 56%|█████▌    | 161/289 [00:27<00:20,  6.10it/s]
 56%|█████▋    | 163/289 [00:27<00:21,  5.98it/s]
 57%|█████▋    | 165/289 [00:28<00:20,  5.97it/s]
 58%|█████▊    | 167/289 [00:28<00:20,  5.87it/s]
 58%|█████▊    | 169/289 [00:28<00:19,  6.06it/s]
 59%|█████▉    | 171/289 [00:29<00:21,  5.59it/s]
 60%|█████▉    | 173/289 [00:29<00:20,  5.61it/s]
 61%|██████    | 175/289 [00:29<00:19,  5.76it/s]
 61%|██████    | 177/289 [00:30<00:18,  6.00it/s]
 62%|██████▏   | 179/289 [00:30<00:19,  5.77it/s]
 63%|██████▎   | 181/289 [00:30<00:18,  5.74it/s]
 63%|██████▎   | 183/289 [00:31<00:17,  5.92it/s]
 64%|██████▍   | 185/289 [00:31<00:18,  5.68it/s]
 65%|██████▍   | 187/289 [00:31<00:16,  6.01it/s]
 65%|██████▌   | 189/289 [00:32<00:16,  5.95it/s]
 66%|██████▌   | 191/289 [00:32<00:16,  6.05it/s]
 67%|██████▋   | 193/289 [00:32<00:16,  5.94it/s]
 67%|██████▋   | 195/289 [00:33<00:15,  6.03it/s]
 68%|██████▊   | 197/289 [00:33<00:15,  6.04it/s]
 69%|██████▉   | 199/289 [00:34<00:15,  5.64it/s]
 70%|██████▉   | 201/289 [00:34<00:15,  5.78it/s]
 70%|███████   | 203/289 [00:34<00:14,  5.83it/s]
 71%|███████   | 205/289 [00:35<00:14,  5.81it/s]
 72%|███████▏  | 207/289 [00:35<00:13,  5.92it/s]
 72%|███████▏  | 209/289 [00:35<00:13,  5.73it/s]
 73%|███████▎  | 211/289 [00:36<00:13,  5.68it/s]
 74%|███████▎  | 213/289 [00:36<00:13,  5.46it/s]
 74%|███████▍  | 215/289 [00:36<00:13,  5.51it/s]
 75%|███████▌  | 217/289 [00:37<00:12,  5.59it/s]
 76%|███████▌  | 219/289 [00:37<00:11,  5.86it/s]
 76%|███████▋  | 221/289 [00:37<00:12,  5.44it/s]
 77%|███████▋  | 223/289 [00:38<00:11,  5.73it/s]
 78%|███████▊  | 225/289 [00:38<00:10,  5.93it/s]
 79%|███████▊  | 227/289 [00:38<00:10,  6.08it/s]
 79%|███████▉  | 229/289 [00:39<00:10,  5.86it/s]
 80%|███████▉  | 231/289 [00:39<00:10,  5.77it/s]
 81%|████████  | 233/289 [00:39<00:09,  5.70it/s]
 81%|████████▏ | 235/289 [00:40<00:09,  5.90it/s]
 82%|████████▏ | 237/289 [00:40<00:08,  5.90it/s]
 83%|████████▎ | 239/289 [00:41<00:08,  5.56it/s]
 83%|████████▎ | 241/289 [00:41<00:08,  5.44it/s]
 84%|████████▍ | 243/289 [00:41<00:08,  5.38it/s]
 85%|████████▍ | 245/289 [00:42<00:07,  5.76it/s]
 85%|████████▌ | 247/289 [00:42<00:07,  5.90it/s]
 86%|████████▌ | 249/289 [00:42<00:06,  5.87it/s]
 87%|████████▋ | 251/289 [00:43<00:06,  5.79it/s]
 88%|████████▊ | 253/289 [00:43<00:06,  5.90it/s]
 88%|████████▊ | 255/289 [00:43<00:05,  5.88it/s]
 89%|████████▉ | 257/289 [00:44<00:05,  5.85it/s]
 90%|████████▉ | 259/289 [00:44<00:05,  5.90it/s]
 90%|█████████ | 261/289 [00:44<00:04,  6.03it/s]
 91%|█████████ | 263/289 [00:45<00:04,  6.33it/s]
 92%|█████████▏| 265/289 [00:45<00:04,  5.99it/s]
 92%|█████████▏| 267/289 [00:45<00:03,  6.18it/s]
 93%|█████████▎| 269/289 [00:46<00:03,  6.13it/s]
 94%|█████████▍| 271/289 [00:46<00:02,  6.11it/s]
 94%|█████████▍| 273/289 [00:46<00:02,  6.39it/s]
 95%|█████████▌| 275/289 [00:47<00:02,  6.10it/s]
 96%|█████████▌| 277/289 [00:47<00:02,  5.93it/s]
 97%|█████████▋| 279/289 [00:47<00:01,  5.95it/s]
 97%|█████████▋| 281/289 [00:48<00:01,  5.84it/s]
 98%|█████████▊| 283/289 [00:48<00:01,  5.99it/s]
 99%|█████████▊| 285/289 [00:48<00:00,  6.39it/s]
 99%|█████████▉| 287/289 [00:49<00:00,  6.11it/s]

 40%|████      | 260/650 [14:41<18:24,  2.83s/it]
100%|██████████| 289/289 [00:49<00:00,  5.94it/s]

{'eval_loss': 0.1024787575006485, 'eval_runtime': 49.4267, 'eval_samples_per_second': 23.368, 'eval_steps_per_second': 5.847, 'epoch': 0.8}

 46%|████▌     | 300/650 [16:34<16:25,  2.81s/it]

{'loss': 0.1044, 'grad_norm': 3.890625, 'learning_rate': 1.088372093023256e-05, 'epoch': 0.92}

 54%|█████▍    | 350/650 [19:05<15:21,  3.07s/it]

{'loss': 0.1022, 'grad_norm': 4.6875, 'learning_rate': 9.333333333333334e-06, 'epoch': 1.08}

 60%|██████    | 390/650 [21:03<12:41,  2.93s/it]
  0%|          | 0/289 [00:00<?, ?it/s]
  1%|          | 2/289 [00:00<00:20, 14.34it/s]
  1%|▏         | 4/289 [00:00<01:03,  4.49it/s]
  2%|▏         | 5/289 [00:01<01:29,  3.18it/s]
  2%|▏         | 7/289 [00:01<01:09,  4.08it/s]
  3%|▎         | 9/289 [00:02<01:00,  4.60it/s]
  4%|▍         | 11/289 [00:02<00:56,  4.91it/s]
  4%|▍         | 13/289 [00:02<00:51,  5.34it/s]
  5%|▌         | 15/289 [00:03<00:49,  5.55it/s]
  6%|▌         | 17/289 [00:03<00:48,  5.61it/s]
  7%|▋         | 19/289 [00:03<00:47,  5.73it/s]
  7%|▋         | 21/289 [00:03<00:43,  6.11it/s]
  8%|▊         | 23/289 [00:04<00:42,  6.22it/s]
  9%|▊         | 25/289 [00:04<00:42,  6.14it/s]
  9%|▉         | 27/289 [00:04<00:42,  6.11it/s]
 10%|█         | 29/289 [00:05<00:42,  6.06it/s]
 11%|█         | 31/289 [00:05<00:42,  6.07it/s]
 11%|█▏        | 33/289 [00:05<00:42,  6.03it/s]
 12%|█▏        | 35/289 [00:06<00:41,  6.08it/s]
 13%|█▎        | 37/289 [00:06<00:42,  5.91it/s]
 13%|█▎        | 39/289 [00:07<00:46,  5.39it/s]
 14%|█▍        | 41/289 [00:07<00:46,  5.33it/s]
 15%|█▍        | 43/289 [00:07<00:45,  5.44it/s]
 16%|█▌        | 45/289 [00:08<00:43,  5.55it/s]
 16%|█▋        | 47/289 [00:08<00:42,  5.76it/s]
 17%|█▋        | 49/289 [00:08<00:40,  5.92it/s]
 18%|█▊        | 51/289 [00:09<00:38,  6.22it/s]
 18%|█▊        | 53/289 [00:09<00:38,  6.18it/s]
 19%|█▉        | 55/289 [00:09<00:37,  6.27it/s]
 20%|█▉        | 57/289 [00:10<00:38,  6.08it/s]
 20%|██        | 59/289 [00:10<00:37,  6.19it/s]
 21%|██        | 61/289 [00:10<00:35,  6.41it/s]
 22%|██▏       | 63/289 [00:10<00:36,  6.25it/s]
 22%|██▏       | 65/289 [00:11<00:38,  5.80it/s]
 23%|██▎       | 67/289 [00:11<00:40,  5.47it/s]
 24%|██▍       | 69/289 [00:12<00:37,  5.79it/s]
 25%|██▍       | 71/289 [00:12<00:38,  5.63it/s]
 25%|██▌       | 73/289 [00:12<00:38,  5.61it/s]
 26%|██▌       | 75/289 [00:13<00:37,  5.67it/s]
 27%|██▋       | 77/289 [00:13<00:37,  5.70it/s]
 27%|██▋       | 79/289 [00:13<00:35,  5.98it/s]
 28%|██▊       | 81/289 [00:14<00:35,  5.85it/s]
 29%|██▊       | 83/289 [00:14<00:34,  5.97it/s]
 29%|██▉       | 85/289 [00:14<00:34,  5.98it/s]
 30%|███       | 87/289 [00:15<00:33,  6.10it/s]
 31%|███       | 89/289 [00:15<00:32,  6.15it/s]
 31%|███▏      | 91/289 [00:15<00:32,  6.01it/s]
 32%|███▏      | 93/289 [00:16<00:34,  5.65it/s]
 33%|███▎      | 95/289 [00:16<00:36,  5.37it/s]
 34%|███▎      | 97/289 [00:16<00:32,  5.87it/s]
 34%|███▍      | 99/289 [00:17<00:32,  5.93it/s]
 35%|███▍      | 101/289 [00:17<00:30,  6.07it/s]
 36%|███▌      | 103/289 [00:17<00:31,  5.89it/s]
 36%|███▋      | 105/289 [00:18<00:29,  6.25it/s]
 37%|███▋      | 107/289 [00:18<00:28,  6.31it/s]
 38%|███▊      | 109/289 [00:18<00:29,  6.19it/s]
 38%|███▊      | 111/289 [00:19<00:30,  5.88it/s]
 39%|███▉      | 113/289 [00:19<00:29,  5.95it/s]
 40%|███▉      | 115/289 [00:19<00:31,  5.55it/s]
 40%|████      | 117/289 [00:20<00:28,  5.99it/s]
 41%|████      | 119/289 [00:20<00:28,  5.99it/s]
 42%|████▏     | 121/289 [00:20<00:26,  6.23it/s]
 43%|████▎     | 123/289 [00:21<00:29,  5.65it/s]
 43%|████▎     | 125/289 [00:21<00:28,  5.74it/s]
 44%|████▍     | 127/289 [00:22<00:28,  5.60it/s]
 45%|████▍     | 129/289 [00:22<00:26,  5.96it/s]
 45%|████▌     | 131/289 [00:22<00:25,  6.20it/s]
 46%|████▌     | 133/289 [00:22<00:25,  6.15it/s]
 47%|████▋     | 135/289 [00:23<00:26,  5.79it/s]
 47%|████▋     | 137/289 [00:23<00:25,  5.89it/s]
 48%|████▊     | 139/289 [00:23<00:24,  6.01it/s]
 49%|████▉     | 141/289 [00:24<00:24,  6.08it/s]
 49%|████▉     | 143/289 [00:24<00:22,  6.38it/s]
 50%|█████     | 145/289 [00:24<00:22,  6.35it/s]
 51%|█████     | 147/289 [00:25<00:22,  6.39it/s]
 52%|█████▏    | 149/289 [00:25<00:22,  6.25it/s]
 52%|█████▏    | 151/289 [00:25<00:22,  6.03it/s]
 53%|█████▎    | 153/289 [00:26<00:23,  5.74it/s]
 54%|█████▎    | 155/289 [00:26<00:23,  5.75it/s]
 54%|█████▍    | 157/289 [00:26<00:22,  5.99it/s]
 55%|█████▌    | 159/289 [00:27<00:22,  5.89it/s]
 56%|█████▌    | 161/289 [00:27<00:20,  6.10it/s]
 56%|█████▋    | 163/289 [00:27<00:21,  5.99it/s]
 57%|█████▋    | 165/289 [00:28<00:20,  5.97it/s]
 58%|█████▊    | 167/289 [00:28<00:20,  5.87it/s]
 58%|█████▊    | 169/289 [00:28<00:19,  6.06it/s]
 59%|█████▉    | 171/289 [00:29<00:21,  5.59it/s]
 60%|█████▉    | 173/289 [00:29<00:20,  5.61it/s]
 61%|██████    | 175/289 [00:30<00:19,  5.76it/s]
 61%|██████    | 177/289 [00:30<00:18,  5.99it/s]
 62%|██████▏   | 179/289 [00:30<00:19,  5.76it/s]
 63%|██████▎   | 181/289 [00:31<00:18,  5.74it/s]
 63%|██████▎   | 183/289 [00:31<00:17,  5.92it/s]
 64%|██████▍   | 185/289 [00:31<00:18,  5.67it/s]
 65%|██████▍   | 187/289 [00:32<00:16,  6.00it/s]
 65%|██████▌   | 189/289 [00:32<00:16,  5.94it/s]
 66%|██████▌   | 191/289 [00:32<00:16,  6.05it/s]
 67%|██████▋   | 193/289 [00:33<00:16,  5.94it/s]
 67%|██████▋   | 195/289 [00:33<00:15,  6.03it/s]
 68%|██████▊   | 197/289 [00:33<00:15,  6.03it/s]
 69%|██████▉   | 199/289 [00:34<00:15,  5.63it/s]
 70%|██████▉   | 201/289 [00:34<00:15,  5.77it/s]
 70%|███████   | 203/289 [00:34<00:14,  5.83it/s]
 71%|███████   | 205/289 [00:35<00:14,  5.81it/s]
 72%|███████▏  | 207/289 [00:35<00:13,  5.93it/s]
 72%|███████▏  | 209/289 [00:35<00:13,  5.73it/s]
 73%|███████▎  | 211/289 [00:36<00:13,  5.68it/s]
 74%|███████▎  | 213/289 [00:36<00:13,  5.46it/s]
 74%|███████▍  | 215/289 [00:36<00:13,  5.50it/s]
 75%|███████▌  | 217/289 [00:37<00:12,  5.58it/s]
 76%|███████▌  | 219/289 [00:37<00:11,  5.85it/s]
 76%|███████▋  | 221/289 [00:37<00:12,  5.43it/s]
 77%|███████▋  | 223/289 [00:38<00:11,  5.72it/s]
 78%|███████▊  | 225/289 [00:38<00:10,  5.92it/s]
 79%|███████▊  | 227/289 [00:38<00:10,  6.06it/s]
 79%|███████▉  | 229/289 [00:39<00:10,  5.85it/s]
 80%|███████▉  | 231/289 [00:39<00:10,  5.76it/s]
 81%|████████  | 233/289 [00:40<00:09,  5.69it/s]
 81%|████████▏ | 235/289 [00:40<00:09,  5.90it/s]
 82%|████████▏ | 237/289 [00:40<00:08,  5.89it/s]
 83%|████████▎ | 239/289 [00:41<00:08,  5.56it/s]
 83%|████████▎ | 241/289 [00:41<00:08,  5.43it/s]
 84%|████████▍ | 243/289 [00:41<00:08,  5.38it/s]
 85%|████████▍ | 245/289 [00:42<00:07,  5.75it/s]
 85%|████████▌ | 247/289 [00:42<00:07,  5.90it/s]
 86%|████████▌ | 249/289 [00:42<00:06,  5.87it/s]
 87%|████████▋ | 251/289 [00:43<00:06,  5.78it/s]
 88%|████████▊ | 253/289 [00:43<00:06,  5.90it/s]
 88%|████████▊ | 255/289 [00:43<00:05,  5.88it/s]
 89%|████████▉ | 257/289 [00:44<00:05,  5.84it/s]
 90%|████████▉ | 259/289 [00:44<00:05,  5.90it/s]
 90%|█████████ | 261/289 [00:44<00:04,  6.03it/s]
 91%|█████████ | 263/289 [00:45<00:04,  6.32it/s]
 92%|█████████▏| 265/289 [00:45<00:04,  5.98it/s]
 92%|█████████▏| 267/289 [00:45<00:03,  6.18it/s]
 93%|█████████▎| 269/289 [00:46<00:03,  6.13it/s]
 94%|█████████▍| 271/289 [00:46<00:02,  6.11it/s]
 94%|█████████▍| 273/289 [00:46<00:02,  6.39it/s]
 95%|█████████▌| 275/289 [00:47<00:02,  6.10it/s]
 96%|█████████▌| 277/289 [00:47<00:02,  5.94it/s]
 97%|█████████▋| 279/289 [00:47<00:01,  5.95it/s]
 97%|█████████▋| 281/289 [00:48<00:01,  5.84it/s]
 98%|█████████▊| 283/289 [00:48<00:01,  6.00it/s]
 99%|█████████▊| 285/289 [00:48<00:00,  6.38it/s]
 99%|█████████▉| 287/289 [00:49<00:00,  6.10it/s]

 60%|██████    | 390/650 [21:52<12:41,  2.93s/it]
100%|██████████| 289/289 [00:49<00:00,  5.95it/s]

{'eval_loss': 0.09796256572008133, 'eval_runtime': 49.485, 'eval_samples_per_second': 23.34, 'eval_steps_per_second': 5.84, 'epoch': 1.2}

 62%|██████▏   | 400/650 [22:20<13:43,  3.29s/it]

{'loss': 0.0969, 'grad_norm': 6.84375, 'learning_rate': 7.782945736434108e-06, 'epoch': 1.23}

 69%|██████▉   | 450/650 [24:42<09:34,  2.87s/it]

{'loss': 0.0957, 'grad_norm': 4.8125, 'learning_rate': 6.2325581395348845e-06, 'epoch': 1.38}

 75%|███████▌  | 488/650 [26:41<08:05,  3.00s/it]

In [ ]:
# from transformers import TextStreamer

In [111]:
# test_idx = 56

# print(dataset_test[test_idx]["user_prompt"])

# messages = [
#     [
#         {'role': 'system','content' : SYSTEM_PROMPT},
#         {"role" : 'user', 'content' : dataset_test[test_idx]["user_prompt"]}
#     ]
# ]
# text = tokenizer.apply_chat_template(
#     messages[0],
#     tokenize = False,
#     add_generation_prompt = True, # Must add for generation
# ).removeprefix('<bos>')

Лет 5 назад был положительный опыт кредитования здесь.
Теперь же взял дебетовую карту на зарплатный проект. Все оформил онлайн. Карту привезли быстро, работает четко. Вопросов нет.

In [135]:
# _ = model.generate(
#     **tokenizer(text, return_tensors = "pt").to("cuda"),
#     max_new_tokens = 125,
#     temperature = 0.5, top_p = 0.95, top_k = 64,
#     streamer = TextStreamer(tokenizer, skip_prompt = True),
# )

# print(dataset_test[test_idx]["conversations"][-1]["content"])

[{'topic': 'Кредиты наличными', 'sentiment': 'positive'}, {'topic': 'Дебетовые карты', 'sentiment': 'positive'}]<end_of_turn>
[{'topic': 'Дебетовые карты', 'sentiment': 'positive'}, {'topic': 'Дистанционное обслуживание', 'sentiment': 'positive'}]

In [ ]:
model.save_pretrained("models/gemma-3-270m-it-revews-fine-tune-v4")  # Local saving
tokenizer.save_pretrained("models/gemma-3-270m-it-revews-fine-tune-v4")

In [ ]:
model.push_to_hub("JosephThePatrician/gemma3-270m-it-reviews-v4", tokenizer, token = "token")

In [ ]:
tokenizer.push_to_hub("JosephThePatrician/gemma3-270m-it-reviews-v4", token = "token")

In [ ]:
model.push_to_hub_merged("JosephThePatrician/gemma3-270m-it-reviews-v3", tokenizer, save_method = "merged_16bit", token = "token")

In [ ]:
model.push_to_hub("JosephThePatrician/gemma3-270m-it-reviews-v3", tokenizer, save_method = "merged_16bit", token = "token")

## Running on the whole dataset

In [29]:
from unsloth import FastLanguageModel
import torch
from itertools import islice
from math import floor

from tqdm.autonotebook import tqdm

In [30]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "mount/models/gemma-3-270m-it-revews-fine-tune-v1", # YOUR MODEL YOU USED FOR TRAINING
    max_seq_length = 2048,
    load_in_4bit = False,
    load_in_8bit = True
)

==((====))==  Unsloth 2025.8.10: Fast Gemma3 patching. Transformers: 4.55.4. vLLM: 0.9.2.
   \\   /|    NVIDIA GeForce RTX 3050 Laptop GPU. Num GPUs = 1. Max memory: 4.0 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 8.6. CUDA Toolkit: 12.6. Triton: 3.3.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

In [ ]:
!ls .cache/huggingface/hub

blobs  refs  snapshots

In [ ]:
# model.save_pretrained_merged("gemma3-270m-it-reviews-v1", tokenizer, save_method = "merged_16bit",)
model.push_to_hub_merged("JosephThePatrician/gemma3-270m-it-reviews-v1", tokenizer, save_method = "merged_16bit", token = "token")

In [ ]:
# model.push_to_hub_merged("JosephThePatrician/gemma3-270m-it-reviews-4bit-v1", tokenizer, save_method = "merged_4bit", token = "token")

In [7]:
model = FastLanguageModel.for_inference(model)

In [18]:
def batched(iterable, n):
    "Batch data into lists of length n. The last batch may be shorter."
    # batched('ABCDEFG', 3) --> ABC DEF G
    it = iter(iterable)
    while True:
        batch = tuple(islice(it, n))
        if not batch:
            return
        yield batch


def make_data_batch(reviews):
    messages = [
        [
            {'role': 'system','content' : SYSTEM_PROMPT},
            {"role" : 'user', 'content' : review}
        ]
        for review in reviews
    ]
    
    texts = tokenizer.apply_chat_template(
        messages,
        tokenize = False,
        add_generation_prompt = True, # Must add for generation
    )
    
    texts = [text.removeprefix('<bos>') for text in texts]
    
    return texts


def predict_batch(reviews, batch_size=2):
    answers = []
    for review_batch in tqdm(batched(reviews, batch_size), total=floor(len(reviews) / batch_size)):
        
        # print(len(review_batch))
        # print(review_batch)
        
        texts = make_data_batch(review_batch)
        
        # print(len(texts))
        # print(texts)
        
        tokens = tokenizer(texts, padding_side="left", padding=True, return_tensors = "pt").to("cuda")
        
        out_tokens = model.generate(
            **tokens,
            max_new_tokens = 256,
            temperature = 0.1, top_p = 0.95, top_k = 64,
            # streamer = TextStreamer(tokenizer, skip_prompt = True),
        )
        
        answer_batch = tokenizer.batch_decode(out_tokens, skip_special_tokens=True)
        answer_batch = [answer_batch[i].split("\nmodel\n")[1] for i in range(len(answer_batch))]
        answers.extend(answer_batch)
    
    return answers

In [13]:
reviews = df["review_text"].values[:50]

In [16]:
predicted_topic_sentiment_pairs = predict_batch(reviews, 12)

  0%|          | 0/4 [00:00<?, ?it/s]

In [12]:
len(predicted_topic_sentiment_pairs)

4778

In [29]:
df.iloc[200]

review_id                                                 948975
date                                                  2025-04-17
review_text    11.04.25Г примерно в 12:30, я, пришёл в ТЦ «Тр...
topic                                               Обслуживание
subtopic                                                     NaN
sentiment                                               Negative
Name: 200, dtype: object

In [32]:
df["review_text"].values[100]

'Отрицательный опыт общения. Полное разочарование. Никому не посоветую открывать вклад в этом банке. Отвратительное обслуживание.'

In [33]:
predicted_topic_sentiment_pairs[100]

"[{'topic': 'Вклады', 'sentiment': 'negative'}, {'topic': 'Офисное обслуживание', 'sentiment': 'negative'}]"

In [16]:
with open("mount/data/predictions_v1.txt", mode="w") as f:
    f.write(str(predicted_topic_sentiment_pairs))

In [42]:
df_structured = pd.read_csv("mount/data/reviews_stuctured.csv")
df_structured

,reviewId,idSiteSpecific,source,date,review_text,topic,subtopic,rating
0,0,1000087,sravni.ru,2025-09-19,Вклад «Новые деньги» невозможно оформить без п...,Вклады,NaN,NaN
1,1,999494,sravni.ru,2025-09-18,В июне 2025 года я порекомендовал премиальную ...,Дебетовые карты,NaN,NaN
2,2,999142,sravni.ru,2025-09-17,Мошенниччиские аперации в интересах Ренессанс ...,Обслуживание,NaN,NaN
3,3,998360,sravni.ru,2025-09-15,Купил услугу Газпром Бонус «Премиум» за 2 990 ...,Дебетовые карты,NaN,NaN
4,4,998516,sravni.ru,2025-09-15,Производил оформление открытия срочного банков...,Вклады,«Накопительный»,NaN
...,...,...,...,...,...,...,...,...
4773,4773,7470,sravni.ru,2011-04-07,Ужастное обслуживание! Мало того потеряли доку...,Обслуживание,NaN,NaN
4774,4774,7049,sravni.ru,2011-03-28,Могут заблокировать рассчетную или кредитную к...,Кредитные карты,NaN,NaN
4775,4775,5221,sravni.ru,2011-01-25,"Мало того уже прошла неделя, а ПТС так и не ве...",Автокредиты,NaN,NaN
4776,4776,5053,sravni.ru,2011-01-16,Газпромбанк– отличный банк с отличными сотрудн...,Ипотека,NaN,NaN
4777,4777,4966,sravni.ru,2011-01-10,В конце концов работают там такие же люди как ...,Кредиты наличными,NaN,NaN

In [43]:
df_review_topics = pd.read_csv("mount/data/reviews_topics.csv")
df_review_topics

        id  reviewId  topicId sentiment
0        0         0        0  Negative
1        1         1        1  Negative
2        2         2        0  Negative
3        3         3       17  Negative
4        4         4       17  Negative
...    ...       ...      ...       ...
4773  4773      4773        2  Negative
4774  4774      4774        4  Negative
4775  4775      4775        8  Negative
4776  4776      4776       17  Positive
4777  4777      4777        6  Positive

[4778 rows x 4 columns]

In [64]:
df_topics_info = pd.read_csv("mount/data/topics_info.csv")
df_topics_info

    id                                name  description
0    0                              Вклады          NaN
1    1                     Дебетовые карты          NaN
2    2                        Обслуживание          NaN
3    3          Дистанционное обслуживание          NaN
4    4                     Кредитные карты          NaN
5    5                   Кредиты наличными          NaN
6    6                       Другие услуги          NaN
7    7                         Обмен валют          NaN
8    8                             Ипотека          NaN
9    9                         Автокредиты          NaN
10  10                Мобильное приложение          NaN
11  11                             Условия          NaN
12  12           Рефинансирование кредитов          NaN
13  13            Рефинансирование ипотеки          NaN
14  14                           Эквайринг          NaN
15  15                Кредитование бизнеса          NaN
16  16                   Денежные переводы          NaN
17  17  17_банке_банком_банка_газпромбанка          NaN

In [40]:
predicted_topic_sentiment_pairs[0]

"[{'topic': 'Вклады', 'sentiment': 'negative'}, {'topic': 'Страховые и сервисные продукты', 'sentiment': 'negative'}]"

In [56]:
ids = []
topics = []
sentiments = []

for i, pairs_str in enumerate(predicted_topic_sentiment_pairs):
    # topics_sentiments_pairs = review["topic_sentiment_pairs"]
    review_id = df_structured["reviewId"][i]
    # print(pairs_str)
    pairs = eval(pairs_str)
    for pair in pairs:
        ids.append(int(review_id))
        topics.append(pair["topic"])
        sentiments.append(pair["sentiment"])

In [27]:
print("123456\r789")

789456

In [ ]:
pd.to_datetime(df["date"]).val

4777   2011-01-10
4776   2011-01-16
4775   2011-01-25
4774   2011-03-28
4773   2011-04-07
          ...
4      2025-09-15
3      2025-09-15
2      2025-09-17
1      2025-09-18
0      2025-09-19
Name: date, Length: 4778, dtype: datetime64[ns]

In [75]:
unique_topics_sorted = pd.Series(topics).value_counts().index.values

unique_topics_ids = list(range(len(unique_topics_sorted)))

topics_ids_dict = {
    unique_topics_sorted[i] : unique_topics_ids[i] for i in range(len(unique_topics_sorted))
}

df_topics_info_v1 = pd.DataFrame(
    {
        "id" : unique_topics_ids,
        "name" : unique_topics_sorted,
        "description" : None
    }
)

# df_topics_info_v1

In [77]:
df_review_topics

        id  reviewId  topicId sentiment
0        0         0        0  Negative
1        1         1        1  Negative
2        2         2        0  Negative
3        3         3       17  Negative
4        4         4       17  Negative
...    ...       ...      ...       ...
4773  4773      4773        2  Negative
4774  4774      4774        4  Negative
4775  4775      4775        8  Negative
4776  4776      4776       17  Positive
4777  4777      4777        6  Positive

[4778 rows x 4 columns]

In [86]:
topicids = [topics_ids_dict[topics[i]] for i in range(len(topics))]

In [90]:
df_topics_sentiments_v1 = pd.DataFrame(
    {
        "id" : list(range(len(ids))),
        "reviewId" : ids,
        "topicId" : topicids,
        "sentiment" : sentiments
    }
)

df_topics_sentiments_v1

        id  reviewId  topicId sentiment
0        0         0        6  negative
1        1         0        7  negative
2        2         1        0  negative
3        3         1       17  negative
4        4         1        1  negative
...    ...       ...      ...       ...
8948  8948      4775        0  negative
8949  8949      4776        4  positive
8950  8950      4776        2  positive
8951  8951      4777        3  negative
8952  8952      4777        2  negative

[8953 rows x 4 columns]

In [91]:
df_topics_info_v1.to_csv("mount/data/structured_data/topics_info.csv", index=False)

df_topics_sentiments_v1.to_csv("mount/data/structured_data/reviews_topics_v1.csv", index=False)